# Generated by Django 5.1.6 on 2025-02-09 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewerprofile',
            name='zoom_account_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='interviewerprofile',
            name='zoom_client_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='interviewerprofile',
            name='zoom_client_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
