# Generated by Django 5.1.6 on 2025-03-07 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewers', '0003_interviewrecording'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewerprofile',
            name='company_name',
            field=models.CharField(default='InsightAI', max_length=255),
        ),
    ]
