# Generated by Django 5.1.6 on 2025-03-07 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interviewers', '0004_interviewerprofile_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewerprofile',
            name='company_name',
        ),
    ]
