# Generated by Django 5.1.6 on 2025-03-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewers', '0005_remove_interviewerprofile_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewerprofile',
            name='company_name',
            field=models.CharField(default='InsightHire', max_length=255),
        ),
    ]
