# Generated by Django 5.1.6 on 2025-03-07 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interviewers', '0004_interviewerverification'),
        ('interviewers', '0006_interviewerprofile_company_name'),
    ]

    operations = [
    ]
