# Generated by Django 5.1.6 on 2025-03-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewers', '0007_merge_20250307_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewerprofile',
            name='company_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewerprofile',
            name='company_linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewerprofile',
            name='company_website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewerprofile',
            name='linkedin_profile',
            field=models.URLField(blank=True, null=True),
        ),
    ]
