# Generated by Django 5.1.6 on 2025-03-03 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_candidateprofile_meeting_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='job_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
