# Generated by Django 5.1.6 on 2025-03-04 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0004_candidateprofile_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='interview_audio/'),
        ),
    ]
