# Generated by Django 5.1.6 on 2025-03-04 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0005_candidateprofile_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='interview_videos/'),
        ),
    ]
