# Generated by Django 5.1.6 on 2025-03-04 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0006_candidateprofile_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='overall_report',
            field=models.TextField(blank=True, null=True),
        ),
    ]
