# Generated by Django 5.1.6 on 2025-03-04 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0007_candidateprofile_overall_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='emotion_analysis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
