# Generated by Django 5.1.6 on 2025-03-07 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0009_jobapplication'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobApplication',
        ),
    ]
