# Generated by Django 5.1.6 on 2025-03-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0010_delete_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='company_applied',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
