# Generated by Django 5.1.6 on 2025-03-07 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0009_candidateverification'),
        ('candidates', '0011_candidateprofile_company_applied'),
    ]

    operations = [
    ]
