# Generated by Django 5.1.6 on 2025-03-09 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0014_candidateprofile_application_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='hiring_recommendation',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
